#!/bin/bash


if [ "${BASH_SOURCE[0]}" == "$0" ]; then
	source ./test_utils.sh
	start_test
fi

# minishell_tester redirects

exec_test 'grep hi <./test_files/infile' 'exit'
exec_test 'grep hi "<infile" <         ./test_files/infile' 'exit'
exec_test 'echo hi < ./test_files/infile bye bye' 'exit'
exec_test 'grep hi <./test_files/infile_big <./test_files/infile' 'exit'
exec_test 'echo <"./test_files/infile" "bonjour       42"' 'exit'
exec_test 'cat <"./test_files/file name with spaces"' 'exit'
exec_test 'cat <./test_files/infile_big ./test_files/infile' 'exit'
exec_test 'cat <"1""2""3""4""5"' 'exit'
exec_test 'echo <"./test_files/infile" <missing <"./test_files/infile"' 'exit'
exec_test 'echo <missing <"./test_files/infile" <missing' 'exit'
exec_test 'cat <"./test_files/infile"' 'exit'
exec_test 'echo <"./test_files/infile_big" | cat <"./test_files/infile"' 'exit'
exec_test 'echo <"./test_files/infile_big" | cat "./test_files/infile"' 'exit'
exec_test 'echo <"./test_files/infile_big" | echo <"./test_files/infile"' 'exit'
exec_test 'echo hi | cat <"./test_files/infile"' 'exit'
exec_test 'echo hi | cat "./test_files/infile"' 'exit'
exec_test 'cat <"./test_files/infile" | echo hi' 'exit'
exec_test 'cat <"./test_files/infile" | grep hello' 'exit'
exec_test 'cat <"./test_files/infile_big" | echo hi' 'exit'
exec_test 'cat <missing' 'exit'
exec_test 'cat <missing | cat' 'exit'
exec_test 'cat <missing | echo oi' 'exit'
exec_test 'cat <missing | cat <"./test_files/infile"' 'exit'
exec_test 'echo <123 <456 hi | echo 42' 'exit'
exec_test 'ls >./outfiles/outfile01' 'exit'
exec_test 'ls >         ./outfiles/outfile01' 'exit'
exec_test 'echo hi >         ./outfiles/outfile01 bye' 'exit'
exec_test 'ls >./outfiles/outfile01 >./outfiles/outfile02' 'exit'
exec_test 'ls >./outfiles/outfile01 >./test_files/invalid_permission' 'exit'
exec_test 'ls >"./outfiles/outfile with spaces"' 'exit'
exec_test 'ls >"./outfiles/outfile""1""2""3""4""5"' 'exit'
exec_test 'ls >"./outfiles/outfile01" >./test_files/invalid_permission >"./outfiles/outfile02"' 'exit'
exec_test 'ls >./test_files/invalid_permission >"./outfiles/outfile01" >./test_files/invalid_permission' 'exit'
exec_test 'cat <"./test_files/infile" >"./outfiles/outfile01"' 'exit'
exec_test 'echo hi >./outfiles/outfile01 | echo bye' 'exit'
exec_test 'echo hi >./outfiles/outfile01 >./outfiles/outfile02 | echo bye' 'exit'
exec_test 'echo hi | echo >./outfiles/outfile01 bye' 'exit'
exec_test 'echo hi | echo bye >./outfiles/outfile01 >./outfiles/outfile02' 'exit'
exec_test 'echo hi >./outfiles/outfile01 | echo bye >./outfiles/outfile02' 'exit'
exec_test 'echo hi >./outfiles/outfile01 >./test_files/invalid_permission | echo bye' 'exit'
exec_test 'echo hi >./test_files/invalid_permission | echo bye' 'exit'
exec_test 'echo hi >./test_files/invalid_permission >./outfiles/outfile01 | echo bye' 'exit'
exec_test 'echo hi | echo bye >./test_files/invalid_permission' 'exit'
exec_test 'echo hi | >./outfiles/outfile01 echo bye >./test_files/invalid_permission' 'exit'
exec_test 'echo hi | echo bye >./test_files/invalid_permission >./outfiles/outfile01' 'exit'
exec_test 'cat <"./test_files/infile" >./test_files/invalid_permission' 'exit'
exec_test 'cat >./test_files/invalid_permission <"./test_files/infile"' 'exit'
exec_test 'cat <missing >./outfiles/outfile01' 'exit'
exec_test 'cat >./outfiles/outfile01 <missing' 'exit'
exec_test 'cat <missing >./test_files/invalid_permission' 'exit'
exec_test 'cat >./test_files/invalid_permission <missing' 'exit'
exec_test 'cat >./outfiles/outfile01 <missing >./test_files/invalid_permission' 'exit'
exec_test 'ls >>./outfiles/outfile01' 'exit'
exec_test 'ls >>      ./outfiles/outfile01' 'exit'
exec_test 'ls >>./outfiles/outfile01 >./outfiles/outfile01' 'exit'
exec_test 'ls >./outfiles/outfile01 >>./outfiles/outfile01' 'exit'
exec_test 'ls >./outfiles/outfile01 >>./outfiles/outfile01 >./outfiles/outfile02' 'exit'
exec_test 'ls >>./outfiles/outfile01 >>./outfiles/outfile02' 'exit'
exec_test 'ls >>./test_files/invalid_permission' 'exit'
exec_test 'ls >>./test_files/invalid_permission >>./outfiles/outfile01' 'exit'
exec_test 'ls >>./outfiles/outfile01 >>./test_files/invalid_permission' 'exit'
exec_test 'ls >./outfiles/outfile01 >>./test_files/invalid_permission >>./outfiles/outfile02' 'exit'
exec_test 'ls <missing >>./test_files/invalid_permission >>./outfiles/outfile02' 'exit'
exec_test 'ls >>./test_files/invalid_permission >>./outfiles/outfile02 <missing' 'exit'
exec_test 'echo hi >>./outfiles/outfile01 | echo bye' 'exit'
exec_test 'echo hi >>./outfiles/outfile01 >>./outfiles/outfile02 | echo bye' 'exit'
exec_test 'echo hi | echo >>./outfiles/outfile01 bye' 'exit'
exec_test 'echo hi | echo bye >>./outfiles/outfile01 >>./outfiles/outfile02' 'exit'
exec_test 'echo hi >>./outfiles/outfile01 | echo bye >>./outfiles/outfile02' 'exit'
exec_test 'echo hi >>./test_files/invalid_permission | echo bye' 'exit'
exec_test 'echo hi >>./test_files/invalid_permission >./outfiles/outfile01 | echo bye' 'exit'
exec_test 'echo hi | echo bye >>./test_files/invalid_permission' 'exit'
exec_test 'echo hi | echo >>./outfiles/outfile01 bye >./test_files/invalid_permission' 'exit'
exec_test 'cat <minishell.h>./outfiles/outfile' 'exit'
exec_test 'cat <minishell.h|ls' 'exit'


if [ "${BASH_SOURCE[0]}" == "$0" ]; then
	end_test
fi